import * as fs from 'fs';
import * as path from 'path';
import type { DB } from '../db';
import { tokenleanHome } from '../config';

export interface ClaudeMdDiff {
  /** Project identifier (cwd path when known, else encoded dir name). */
  project: string;
  /** Ready-to-copy diff block of proposed CLAUDE.md additions. */
  diff: string;
  /** The deduplicated suggestion lines behind the diff. */
  lines: string[];
}

/** Only these categories produce CLAUDE.md lines (SPEC §4.4). */
export const CLAUDE_MD_CATEGORIES = ['missing_convention', 'resupplied_context'] as const;

const UNKNOWN_PROJECT = '(unknown project)';

/**
 * Normalize one proposed line: collapse whitespace, strip any existing
 * bullet marker, and re-prefix with "- ". Returns null for empty input.
 */
export function normalizeClaudeMdLine(raw: string): string | null {
  let line = raw.replace(/\s+/g, ' ').trim();
  if (!line) return null;
  line = line.replace(/^[-*•]+\s*/, '').trim();
  if (!line) return null;
  return `- ${line}`;
}

/**
 * Aggregate missing_convention / resupplied_context findings into one
 * deduplicated proposed CLAUDE.md diff per project (SPEC §4.4–4.5).
 * Lines are deduped per project case-insensitively after whitespace
 * normalization; first occurrence wins.
 */
export function buildClaudeMdDiffs(db: DB): ClaudeMdDiff[] {
  const rows = db
    .prepare(
      `SELECT f.claude_md_line AS line, COALESCE(s.project, ?) AS project
       FROM findings f LEFT JOIN sessions s ON s.id = f.session_id
       WHERE f.claude_md_line IS NOT NULL AND TRIM(f.claude_md_line) <> ''
         AND f.category IN ('missing_convention', 'resupplied_context')
       ORDER BY f.id`
    )
    .all(UNKNOWN_PROJECT) as { line: string; project: string }[];

  const byProject = new Map<string, { seen: Set<string>; lines: string[] }>();
  for (const row of rows) {
    const normalized = normalizeClaudeMdLine(row.line);
    if (!normalized) continue;
    let entry = byProject.get(row.project);
    if (!entry) {
      entry = { seen: new Set(), lines: [] };
      byProject.set(row.project, entry);
    }
    const key = normalized.toLowerCase();
    if (entry.seen.has(key)) continue;
    entry.seen.add(key);
    entry.lines.push(normalized);
  }

  const diffs: ClaudeMdDiff[] = [];
  for (const [project, { lines }] of byProject) {
    const diff = [
      '--- a/CLAUDE.md',
      '+++ b/CLAUDE.md',
      '@@ proposed by tokenlean @@',
      ...lines.map((l) => `+${l}`),
    ].join('\n');
    diffs.push({ project, diff, lines });
  }
  diffs.sort((a, b) => a.project.localeCompare(b.project));
  return diffs;
}

/**
 * Write each project's proposal to CLAUDE.md.suggested beside the target
 * CLAUDE.md. NEVER edits CLAUDE.md itself. Projects whose directory does
 * not exist on this machine get their proposal written under
 * <tokenleanHome()>/suggestions/ instead. Returns written paths.
 */
export function writeClaudeMdSuggestions(db: DB): string[] {
  const diffs = buildClaudeMdDiffs(db);
  const written: string[] = [];
  for (const d of diffs) {
    const header = [
      '<!--',
      '  Proposed CLAUDE.md additions, generated by tokenlean.',
      '  Review each line and merge the keepers into CLAUDE.md manually.',
      '  tokenlean never writes or modifies CLAUDE.md itself.',
      '-->',
      '',
    ].join('\n');
    const body = header + d.lines.join('\n') + '\n';

    let target: string;
    if (isDirectory(d.project)) {
      target = path.join(d.project, 'CLAUDE.md.suggested');
    } else {
      const dir = path.join(tokenleanHome(), 'suggestions');
      fs.mkdirSync(dir, { recursive: true });
      target = path.join(dir, `${sanitizeProjectName(d.project)}.suggested`);
    }
    fs.writeFileSync(target, body, 'utf8');
    written.push(target);
  }
  return written;
}

/** Encode a project path into a safe flat filename. */
export function sanitizeProjectName(project: string): string {
  const safe = project.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
  return safe || 'project';
}

function isDirectory(p: string): boolean {
  try {
    return fs.statSync(p).isDirectory();
  } catch {
    return false;
  }
}
