"use client";
import {useMemo,useState} from"react";
const findings=[
["High","Missing convention","Your test framework keeps getting restated","“No, use Vitest — this repo doesn’t use Jest.”","Add the test runner and preferred commands to CLAUDE.md once."],
["High","Resupplied context","The same deployment notes appeared in 4 sessions","A 620-character Cloudflare note was pasted repeatedly.","Move stable deployment notes into CLAUDE.md and reference the file."],
["Medium","Overscoped ask","Large requests are creating partial restarts","Three prompts combined UI, database, tests, and deployment.","Name one outcome and its acceptance check first."],
["Low","Oversized paste","Two code blocks could have been file references","11,840 characters pasted from files already available.","Give the file path and exact area to inspect."]
];
export default function Home(){const[filter,setFilter]=useState("All"),[gone,setGone]=useState<number[]>([]),[copied,setCopied]=useState(false);const items=useMemo(()=>findings.filter((x,i)=>!gone.includes(i)&&(filter==="All"||x[0]===filter)),[filter,gone]);const copy=async()=>{await navigator.clipboard?.writeText("+ Testing: use Vitest. Run npm test before completing a change.\n+ Deployment: target Cloudflare Workers; preserve streaming responses.");setCopied(true);setTimeout(()=>setCopied(false),1500)};return <main>
<header><a className="brand" href="#overview"><b>tl</b>tokenlean</a><nav>{["Overview","Findings","Sessions","CLAUDE.md","Impact"].map(x=><a href={"#"+x.toLowerCase().replace(".","")} key={x}>{x}</a>)}</nav><span className="local">● Local only</span></header>
<section className="hero" id="overview"><div><p className="eyebrow">PROMPT EFFICIENCY, MEASURED HONESTLY</p><h1>Less rework.<br/><em>Leaner sessions.</em></h1><p className="lede">See where your Claude Code sessions lose momentum, then fix the habits and project context that cause it.</p></div><aside><label>REPORTING PERIOD</label><select><option>Last 30 days</option><option>Last 7 days</option><option>Last 90 days</option></select><p><strong>42 sessions</strong> analyzed on this device</p><small>Demo data · no transcript leaves your browser</small></aside></section>
<section className="scores"><article className="primary"><span>Efficiency score <i>↑ 8 pts</i></span><strong className="big">78<small>/ 100</small></strong><div className="meter"><b/></div><p>Repeated context is the largest remaining opportunity.</p></article><article><span>Correction rate <i>↓ 3.2%</i></span><strong>9.4%</strong><p>4 of 43 turns corrected prior work.</p></article><article><span>Tokens per task <i>↓ 12%</i></span><strong>48.2k</strong><p>Down from your baseline of 54.8k.</p></article><article><span>Analysis overhead <mark>ON BUDGET</mark></span><strong>1.6%</strong><p>31k tokens spent analyzing 1.94M.</p></article></section>
<section className="section" id="findings"><div className="title"><div><p className="eyebrow">WHAT TO FIX NEXT</p><h2>Findings worth your attention</h2></div><div className="filters">{["All","High","Medium","Low"].map(x=><button className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="findings">{items.map((x,i)=><article key={x[2]}><span className="num">0{i+1}</span><div><small>{x[1]} · <b>{x[0]} IMPACT</b></small><h3>{x[2]}</h3><p className="quote">{x[3]}</p><p>{x[4]}</p></div><button className="close" onClick={()=>setGone([...gone,findings.indexOf(x)])} aria-label="Dismiss">×</button></article>)}{!items.length&&<p className="empty">Nothing left in this filter. Nice work.</p>}</div></section>
<section className="diff" id="claudemd"><div><p className="eyebrow">YOUR HIGHEST-LEVERAGE EDIT</p><h2>Make project context reusable</h2><p>These conventions appeared after Claude had already started work. Add them once and future sessions begin with the right defaults.</p><blockquote>tokenlean never changes CLAUDE.md directly. Review and copy this suggestion when it looks right.</blockquote></div><div className="code"><div>CLAUDE.md · suggested <button onClick={copy}>{copied?"Copied":"Copy plain text"}</button></div><pre>+ Testing: use Vitest. Run npm test before completing a change.{"\n"}+ Deployment: target Cloudflare Workers; preserve streaming responses.</pre><section><b>Why this helps</b><p>Claude sees these instructions at the start of every session. You no longer repeat them after an incorrect choice.</p></section></div></section>
<section className="section" id="sessions"><p className="eyebrow">SESSION EXPLORER</p><h2>Where the score came from</h2><div className="table"><table><thead><tr><th>Project and task</th><th>Turns</th><th>Tokens</th><th>Corrections</th><th>Status</th></tr></thead><tbody>{[["Refine onboarding flow","18","82.4k","3","Needs review"],["Build project gallery","9","31.7k","0","Lean"],["Debug streaming response","14","57.1k","2","Needs review"],["Set up test coverage","7","24.9k","1","Improving"]].map(s=><tr key={s[0]}>{s.map((v,i)=><td key={v}>{i===0?<b>{v}</b>:v}</td>)}</tr>)}</tbody></table></div></section>
<section className="impact" id="impact"><div><p className="eyebrow">ROUGH ENVIRONMENTAL ESTIMATE</p><h2>Small savings,<br/>compounded over time.</h2><p>Based on 286k fewer tokens than your baseline. No first-party energy figures exist for Claude, so these are ranges—not promises.</p></div><div className="impactnums"><article><span>Estimated energy avoided</span><strong>0.09–0.29</strong><small>kWh</small></article><article><span>Estimated water avoided</span><strong>0.10–3.48</strong><small>litres</small></article><p>Assumptions: 0.3–1.0 kWh per million uncached tokens; 1.1–12 L water per kWh.</p></div></section>
<footer><span className="brand"><b>tl</b>tokenlean</span><span>Open source. Local-first. Never blocks a prompt.</span><span>Analysis demo · July 2026</span></footer>
</main>}
